### PR TITLE
#31 - set up dependabot

### LINKED ISSUE #31: Set up Dependabot
> To get started with Dependabot version updates, you'll need to specify which package ecosystems to update and where the package manifests are located. Please see the documentation for all configuration options: https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

### PR DESCRIPTION
**Pull request by krzysztofrewak**
Should close #31

### CODE REVIEW

**Review by mateuszchodor — COMMENTED** [review]
I think we should set at what time it will check updates and set timezone

**Comment by krzysztofrewak** [comment]
> I think we should set at what time it will check updates and set timezone

TBH I don't care on what time it will be triggered. What would you suggest?

**Comment by mateuszchodor** [comment]
I propose 7 am

**Review by mateuszchodor — DISMISSED** [review]
Very good.

**Pull request merged**
